### ISSUE TITLE
pds-generate crashes when runs out of heap memory

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/mi-label#31]
## 🐛 Describe the bug

When trying to run pds-generate on 1274 PDS3 lbl files that are more than 2 MB each
it crashes with the below error output

pds-generate -p data/*/*.lbl -t Template_test.vm 
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.antlr.runtime.ANTLRReaderStream.load(ANTLRReaderStream.java:78)
	at org.antlr.runtime.ANTLRInputStream.<init>(ANTLRInputStream.java:68)
	at org.antlr.runtime.ANTLRInputStream.<init>(ANTLRInputStream.java:52)
	at org.antlr.runtime.ANTLRInputStream.<init>(ANTLRInputStream.java:48)
	at org.antlr.runtime.ANTLRInputStream.<init>(ANTLRInputStream.java:40)
	at gov.nasa.pds.tools.label.parser.DefaultLabelParser.parseLabel(DefaultLabelParser.java:265)
	at gov.nasa.pds.tools.label.parser.DefaultLabelParser.parseLabel(DefaultLabelParser.java:249)
	at gov.nasa.pds.tools.label.parser.DefaultLabelParser.parseLabel(DefaultLabelParser.java:154)
	at gov.nasa.pds.imaging.generate.readers.ProductToolsLabelReader.parseLabel(ProductToolsLabelReader.java:302)
	at gov.nasa.pds.imaging.generate.label.PDS3Label.setMappings(PDS3Label.java:463)
	at gov.nasa.pds.imaging.generate.GenerateLauncher.query(GenerateLauncher.java:225)
	at gov.nasa.pds.imaging.generate.GenerateLauncher.main(GenerateLauncher.java:293)

It should be noted that no PDS4 xml labels were produced.
When test were run using small numbers of products (1, 2, 5, and 10) it was noted that the percentage of memory
used from the beginning increased with the number of products included, increased as processing time passed,
and was not seen to decrease.

## 📜 To Reproduce
1. Go to 'https://pdssbn.astro.umd.edu/holdings/nh-a-pepssi-3-kem1-v5.0/dataset.shtml'
2. Click on 'DOWNLOAD (1010.3 MB)'
3. Download the checksum and tgz file
4. confirm the checksum and open the tgz file 
5. cd to nh-a-pepssi-3-kem1-v5.0
6. run pds-generate -p data/*/*.lbl -t Template_test.vm 
7. See error

## 🕵️ Expected behavior

PDS4 xml labels to be produced for each PDS3 lbl label and the program to not crash.

## 📚 Version of Software Used

/sbnops/lcltools/bin/pds-generate -V

gov.nasa.pds:mi-label
Version 1.2.2
Release Date: 2022-04-14 05:41:49

## 🩺 Test Data / Additional context

See Reproduce section and (I owe you a template - need one for the data that is public)

## 🖥 System Info
 - OS: [e.g. iOS] RHEL 3.10.0-1160.66.1.el7.x86_64 number 1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Browser [e.g. chrome, safari] n/a

---

**Comment by jordanpadams** [comment]
@plawton-umd per our discussion, this may be an error in the MILabel logic, or a memory leak.

in the meantime, a workaround that may help get this working would be to increase your Java heap by updating the last line of `pds-generate` command-line script.

Before:
```bash
${JAVA_CMD} -jar ${GENERATE_JAR} "$@"
```

After:
```bash
"${JAVA_CMD}" -Xms2048m -Xmx4096m -jar ${GENERATE_JAR} "$@"
```

Depending upon how much available memory you have and what you are running on the server you are executing MILabel, you can can continue to multiply each of those numbers x2 until it stops failing. This is a temporary spike in the memory usage while the software runs, but Java garbage collection will clean it all up as soon as (or very very soon as after) the run completes.

let me know how this goes. we will add this to our backlog to investigate the issue further.

**Comment by jordanpadams** [comment]
@plawton-umd As a heads up, we have not had an opportunity to push the testing of this app to determine the guaranteed issue here, but we just fixed a potential memory leak in the code that may have been a cause for this.
